#!/usr/bin/env bash
#
# MATRYXX LLC · Wingman.OS — local live stack wizard
# Walks through venv, .env.local, smoke, three dashboards, optional GitHub push.
# Generated by /wizard skill.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — do not hand-edit below this block in forks; replace stages only.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

TOTAL_STAGES=0
TOTAL_MINUTES=0

_STAGE_INDEX=0
_MINUTES_ELAPSED=0
ENV_FILE="${ENV_FILE:-.env.local}"
WRITTEN_ENV=()
WRITTEN_SECRET=()
SKIPPED=()

_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages · about %s minutes%s\n\n' \
    "$DIM" "$TOTAL_STAGES" "$TOTAL_MINUTES" "$RESET"
  printf '%s  Operated by MATRYXX LLC (Sheridan, WY). Product: Wingman.OS.%s\n' "$DIM" "$RESET"
  printf '%s  Fictional vessel ledger — not a brokerage, not a chain, not advice.%s\n\n' "$DIM" "$RESET"
  pause "Ready to start?"
}

stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  local remaining=$((TOTAL_MINUTES - _MINUTES_ELAPSED))
  (( remaining < 0 )) && remaining=0
  _MINUTES_ELAPSED=$((_MINUTES_ELAPSED + ${2:-0}))
  printf '\n%s%s▸ Stage %s/%s · %s%s  %s(~%s min left)%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET" "$DIM" "$remaining" "$RESET"
}

say()  { printf '  %s\n' "$1"; }
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit manually: $url"
}

pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && env -u GH_TOKEN -u GITHUB_TOKEN gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | env -u GH_TOKEN -u GITHUB_TOKEN gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready"
}

set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && env -u GH_TOKEN -u GITHUB_TOKEN gh auth status >/dev/null 2>&1; then
    if env -u GH_TOKEN -u GITHUB_TOKEN gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready"
}

finish() {
  _clear
  printf '\n%s%s  ✓ Live stack wizard complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES
# ──────────────────────────────────────────────────────────────────────────

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
BACKEND="$REPO_ROOT/backend"
ENV_FILE="$REPO_ROOT/.env.local"

TOTAL_STAGES=8
TOTAL_MINUTES=18

banner "MATRYXX LLC · Sacred Loop live stack"

# 1 — Prerequisites
stage "Prerequisites" 2
say "You need Python 3.12+, curl, and optional gh (GitHub CLI) for push."
step "Verify Python:"
if ! command -v python3 >/dev/null 2>&1; then
  warn "python3 not found — install Python 3.12+ and re-run."
  exit 1
fi
note "  $(python3 --version)"
step "If gh push fails with 401, invalid GH_TOKEN/GITHUB_TOKEN env vars override keyring."
note "  Fix: env -u GH_TOKEN -u GITHUB_TOKEN gh auth status"
pause

# 2 — Venv + deps
stage "Backend venv" 4
say "Creating isolated venv in backend/.venv and installing requirements."
step "Run pip install (this may take a minute)."
if [[ ! -d "$BACKEND/.venv" ]]; then
  python3 -m venv "$BACKEND/.venv"
fi
# shellcheck disable=SC1091
source "$BACKEND/.venv/bin/activate"
pip install -q -r "$BACKEND/requirements.txt"
pip install -q pytest
write_env "VENV_PYTHON" "$BACKEND/.venv/bin/python"
note "  pytest + fastapi installed."
pause

# 3 — Ports & paths
stage "Ports and API base URL" 3
say "Defaults match the live session: desk :8081, mockup :8090, artifact :8091."
ask DESK_API_PORT "Desk API port (uvicorn):"
DESK_API_PORT="${DESK_API_PORT:-8081}"
ask MOCKUP_PORT "Sacred-loop mockup (static index.html):"
MOCKUP_PORT="${MOCKUP_PORT:-8090}"
ask ARTIFACT_PORT "Wingman.OS artifact dist (vite build):"
ARTIFACT_PORT="${ARTIFACT_PORT:-8091}"
ask ARTIFACT_DIST "Full path to wingman-os-artifact/dist:"
ARTIFACT_DIST="${ARTIFACT_DIST:-$HOME/wingman-os-artifact/dist}"
ask DATABASE_PATH "SQLite path for desk ledger:"
DATABASE_PATH="${DATABASE_PATH:-/tmp/desk-live.db}"
DESK_API_BASE="http://127.0.0.1:${DESK_API_PORT}"
write_env DESK_API_PORT "$DESK_API_PORT"
write_env MOCKUP_PORT "$MOCKUP_PORT"
write_env ARTIFACT_PORT "$ARTIFACT_PORT"
write_env ARTIFACT_DIST "$ARTIFACT_DIST"
write_env DATABASE_PATH "$DATABASE_PATH"
write_env DESK_API_BASE "$DESK_API_BASE"
write_env GITHUB_REPO "gothamgodzilla/dj-matryxx-sacred-loop"
pause

# 4 — Tests
stage "Run backend tests" 2
step "pytest backend/tests (4 tests)."
cd "$BACKEND"
export DATABASE_PATH
"$BACKEND/.venv/bin/python" -m pytest -q tests/
note "  All tests should pass."
pause

# 5 — Branding gate
stage "Branding check" 1
step "Product surfaces must not ship Coexist branding (docs may mention replacement)."
if rg -i "coexist" "$REPO_ROOT/index.html" "$REPO_ROOT/assets" "$REPO_ROOT/backend" >/dev/null 2>&1; then
  warn "Found 'coexist' in product files — fix before release."
else
  note "  ✓ product surfaces clean (rg exit 1)."
fi
pause

# 6 — Generate start script
stage "Write start script" 2
START_SCRIPT="$SCRIPT_DIR/run-live-stack.sh"
cat > "$START_SCRIPT" <<EOF
#!/usr/bin/env bash
# Generated by live-stack-wizard.sh — starts desk API, mockup, artifact static servers.
set -euo pipefail
ROOT="$REPO_ROOT"
BACKEND="$BACKEND"
# shellcheck source=/dev/null
source "$ENV_FILE" 2>/dev/null || true
export DATABASE_PATH="\${DATABASE_PATH:-$DATABASE_PATH}"
DESK_API_PORT="\${DESK_API_PORT:-$DESK_API_PORT}"
MOCKUP_PORT="\${MOCKUP_PORT:-$MOCKUP_PORT}"
ARTIFACT_PORT="\${ARTIFACT_PORT:-$ARTIFACT_PORT}"
ARTIFACT_DIST="\${ARTIFACT_DIST:-$ARTIFACT_DIST}"
PIDFILE="\$ROOT/.live-stack.pids"
: > "\$PIDFILE"
cd "\$BACKEND"
"\$BACKEND/.venv/bin/python" -m uvicorn app.main:app --host 127.0.0.1 --port "\$DESK_API_PORT" &
echo \$! >> "\$PIDFILE"
cd "\$ROOT"
python3 -m http.server "\$MOCKUP_PORT" &
echo \$! >> "\$PIDFILE"
cd "\$ARTIFACT_DIST"
python3 -m http.server "\$ARTIFACT_PORT" &
echo \$! >> "\$PIDFILE"
echo "Desk API:  http://127.0.0.1:\$DESK_API_PORT/health"
echo "Mockup:    http://127.0.0.1:\$MOCKUP_PORT/index.html"
echo "Artifact:  http://127.0.0.1:\$ARTIFACT_PORT/index.html"
echo "Stop: kill \$(tr '\\n' ' ' < "\$PIDFILE")"
EOF
chmod +x "$START_SCRIPT"
note "  Wrote $START_SCRIPT"
if confirm "Start the live stack now"; then
  bash "$START_SCRIPT"
  sleep 3
else
  note "  Start later: $START_SCRIPT"
fi
pause

# 7 — Smoke
stage "Smoke desk API" 2
step "Run backend/smoke_desk.py against DESK_API_BASE."
export DESK_API_BASE
# smoke uses hardcoded 8080 — patch via sed for this run or env
SMOKE="$BACKEND/smoke_desk.py"
TMP=$(mktemp)
sed "s|http://127.0.0.1:8080|$DESK_API_BASE|g" "$SMOKE" > "$TMP"
"$BACKEND/.venv/bin/python" "$TMP"
rm -f "$TMP"
note "  Expected: SMOKE OK"
pause

# 8 — Open dashboards + optional push
stage "Open dashboards · optional GitHub push" 4
open_url "http://127.0.0.1:${MOCKUP_PORT}/index.html"
open_url "http://127.0.0.1:${DESK_API_PORT}/desk/today"
open_url "http://127.0.0.1:${ARTIFACT_PORT}/index.html"
open_url "https://github.com/gothamgodzilla/dj-matryxx-sacred-loop"
if confirm "Push latest subtree to GitHub now (requires gh auth)"; then
  step "From your home git root, subtree split + push (only dj-matryxx-sacred-loop/)."
  note "  cd ~ && git subtree split --prefix dj-matryxx-sacred-loop -b tmp-sacred-push"
  note "  env -u GH_TOKEN -u GITHUB_TOKEN git push https://github.com/gothamgodzilla/dj-matryxx-sacred-loop.git tmp-sacred-push:main"
  note "  git branch -D tmp-sacred-push"
  warn "Wizard does not auto-push — run the commands above if you confirmed."
  SKIPPED+=("GitHub push (run subtree commands manually after review)")
else
  note "  Skipped push — local stack only."
fi
pause

finish
note "Run again anytime: bash $SCRIPT_DIR/live-stack-wizard.sh"
note "Quick start after first run: bash $START_SCRIPT"
